openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: API для докладов
servers:
  - url: http://localhost:8888
    description: Example server
paths:
  /orall:
    get:
      summary: Чтение информации о всех докладах
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orders'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /orders:
    get:
      summary: Чтение информации о докладе
      parameters:
      - name: user_id
        description: Уникальный идентификатор пользователя
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/id'
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orders'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order:
    get:
      summary: Чтение информации о докладе
      parameters:
      - name: id
        description: Уникальный идентификатор доклада
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/id'
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Обновление информации о докладе
      parameters:
      - name: id
        description: Идентификатор доклада
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: user_id
        description: Идентификатор пользователя
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: type
        description: Тип доклада
        in: query
        required: true
        schema:
          type: string
      - name: rate
        description: Рейтинг доклада 
        in: query
        required: true
        schema:
          type: integer
      - name: name
        description: Название доклада
        in: query
        required: true
        schema:
          type: string
      - name: description
        description: Краткое описание
        in: query
        required: true
        schema:
          type: string
      - name: topic
        description: Ключевые слова
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового доклада
      parameters:
      - name: id
        description: Идентификатор доклада
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: user_id
        description: Идентификатор пользователя
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: type
        description: Тип доклада
        in: query
        required: true
        schema:
          type: string
      - name: rate
        description: Рейтинг доклада 
        in: query
        required: true
        schema:
          type: integer
      - name: name
        description: Название доклада
        in: query
        required: true
        schema:
          type: string
      - name: description
        description: Краткое описание
        in: query
        required: true
        schema:
          type: string
      - name: topic
        description: Ключевые слова
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Удаление доклада
      parameters:
      - name: id
        description: Идентификатор доклада
        in: query
        required: true
        schema:
          type: integer
          default: 1
    
      responses:
        '200':
          description: Идентификатор, удаленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    id:
      description: Уникальный идентификатор
      type: integer
    orders:
      type: array
      items:
        $ref: '#/components/schemas/order'
    order:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        type:
          type: string
        name:
          type: string
        rate:
          type: integer
        description:
          type: object
          properties:
            topic:
              type: string
            descriptions:
              type: string


    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:     
      type: http
      scheme: basic
security:
  - bearerAuth: []
  - basicAuth: []